"""init

Revision ID: cfab70c5a0eb
Revises: 
Create Date: 2021-04-14 08:58:39.007504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfab70c5a0eb'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('camera', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_captures'))
    )
    op.create_index('index_id', 'captures', ['id'], unique=True, mysql_length=255)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('index_id', table_name='captures')
    op.drop_table('captures')
    # ### end Alembic commands ###
