"""init

Revision ID: 7826ec1b6833
Revises: 
Create Date: 2021-04-17 20:06:05.611928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7826ec1b6833'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('created at', sa.DateTime(), nullable=True),
    sa.Column('camera', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('capture_id', 'captures', ['id'], unique=True, mysql_length=255)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('password', sa.Unicode(length=128), nullable=False),
    sa.Column('hash_algorithm', sa.Enum('sha3_384', 'shake_256', 'sha3_224', 'sha1', 'sha384', 'shake_128', 'sha256', 'blake2b', 'blake2s', 'sha3_256', 'sha3_512', 'sha512', 'sha224', 'md5', name='hash_algorithms_enum'), nullable=False),
    sa.Column('salt', sa.Unicode(length=128), nullable=False),
    sa.Column('reset_key', sa.String(length=255), nullable=True),
    sa.Column('email', sa.Unicode(length=254), nullable=False),
    sa.Column('new_email', sa.Unicode(length=254), nullable=True),
    sa.Column('email_change_key', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Unicode(length=32), nullable=True),
    sa.Column('firstname', sa.Unicode(length=100), nullable=True),
    sa.Column('lastname', sa.Unicode(length=100), nullable=True),
    sa.Column('activate_key', sa.String(length=255), nullable=True),
    sa.Column('address_ip', sa.String(length=15), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activate_key'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email_change_key'),
    sa.UniqueConstraint('new_email'),
    sa.UniqueConstraint('reset_key'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_authentication_provider',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Unicode(length=15), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'provider'),
    sa.UniqueConstraint('provider', 'provider_id', name='user_authentication_methods_provider_id')
    )
    op.create_table('users_groups',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_groups')
    op.drop_table('user_authentication_provider')
    op.drop_table('users')
    op.drop_table('groups')
    op.drop_index('capture_id', table_name='captures')
    op.drop_table('captures')
    # ### end Alembic commands ###
