"""init

Revision ID: 8af3a76eda6a
Revises: 
Create Date: 2021-04-14 10:21:57.585375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8af3a76eda6a'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('created at', sa.String(), nullable=True),
    sa.Column('camera', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_captures'))
    )
    op.create_index('index_id', 'captures', ['id'], unique=True, mysql_length=255)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index('index_id', table_name='captures')
    op.drop_table('captures')
    # ### end Alembic commands ###
